<?php

$EM_CONF[$_EXTKEY] = array(
        'title' => 'Site',
        'description' => '',
        'category' => 'misc',
        'shy' => 0,
        'version' => '1.0.0',
        'dependencies' => 'extbase,fluid',
        'conflicts' => '',
        'priority' => '',
        'loadOrder' => '',
        'module' => '',
        'state' => 'beta',
        'uploadfolder' => 1,
        'createDirs' => '',
        'modify_tables' => '',
        'clearCacheOnLoad' => 1,
        'lockType' => '',
        'author' => 'Tobias Liebig',
        'author_email' => 'work@etobi.de',
        'author_company' => 'etobi',
        'CGLcompliance' => '',
        'CGLcompliance_note' => '',
        'constraints' => array(
                'depends' => array(
                        'php' => '5.4.0-0.0.0',
                        'typo3' => '7.6.0-7.6.99',
                ),
                'conflicts' => array(),
                'suggests' => array(),
        ),
        'suggests' => array(),
        '_md5_values_when_last_written' => '',
);
